config/routes.rb
Igata::Application.routes.draw do
  root :to => 'landing#show'
  easy_auth_routes
  dismissible_helpers_routes

  # Template Demos
  get     '/template_demos/:id/status' => 'template_demos_status#show', :as => :template_demos_status
  delete  '/template_demos/:id'        => 'template_demos#destroy',     :as => :template_demo

  # Purchased Templates
  get    '/template_purchases/:id/status' => 'template_purchases_status#show', :as => :template_purchase_status
  delete '/template_purchases/:id'       => 'template_purchases#destroy',     :as => :template_purchase
  get    '/my_purchases'                  => 'template_purchases#index',       :as => :purchased_templates

  # Remote repositories
  get '/repositories/readme'   => 'repositories#readme', :as => :readme_repository
  get '/repositories/addons'   => 'repositories#addons', :as => :addons_repository
  get '/repositories/:service' => 'repositories#index', :as => :repositories

  # MyTemplates
  get    '/my_templates'                  => 'my_templates#index',             :as => :my_templates
  get    '/my_templates/new'              => 'my_templates#new',               :as => :new_template
  post   '/my_templates/new'              => 'my_templates#create'
  get    '/my_templates/:id/edit'         => 'my_templates#edit',              :as => :edit_template
  put    '/my_templates/:id/edit'         => 'my_templates#update'
  delete '/my_templates/:id/edit'         => 'my_templates#destroy'
  get    '/my_templates/:id/clone_status' => 'my_templates_clone_status#show', :as => 'my_template_clone_status'
  get    '/my_templates/:template_id/screenshots/new' => 'screenshots#new',     :as => :new_screenshot
  post   '/my_templates/:template_id/screenshots/new' => 'screenshots#create',  :as => :new_screenshot
  delete '/my_templates/:template_id/screenshots/:id' => 'screenshots#destroy', :as => :screenshot

  # Accounts
  get  '/account/edit' => 'accounts#edit',   :as => :edit_account
  put  '/account/edit' => 'accounts#update'
  get  '/sign_up'      => 'accounts#new',    :as => :sign_up
  post '/sign_up'      => 'accounts#create'

  # Dashboard
  get  '/dashboard' => 'dashboard#show', :as => :dashboard


  pages :about, :contact, :legal, :how_it_works
  get  '/:username' => 'profiles#show', :as => :profile
  get  '/:username/:id' => 'templates#show', :as => :template
  post '/:username/:id/purchase'     => 'template_purchases#create',  :as => :purchase_template
  get  '/:username/:id/can_purchase' => 'template_purchases#can_purchase',  :as => :can_purchase_template
  post '/:username/:id/demo'         => 'template_demos#create',      :as => :demo_template
  get  '/:username/:id/can_demo'     => 'template_demos#can_demo',    :as => :can_demo_template
end

app/controllers/my_templates_controller.rb
class MyTemplatesController < AuthenticatedController
  before_filter :find_template, :only => [:edit, :update, :destroy]

  def index
    @templates = current_account.templates
  end

  def new
    @template = Template.new
  end

  def update
    if @template.update_attributes(params[:template])
      redirect_to [:edit, @template]
    else
      render :edit
    end
  end

  def create
    @template = current_account.templates.build(params[:template])

    if @template.save
      @template.update_column :state, 1001
      Resque.enqueue(Template, 'clone_repo', @template.id)
      redirect_to my_templates_path, :notice => "Your template, #{@template.name}, has been created"
    else
      render :new
    end
  end

  def destroy
    if @template.destroy
      redirect_to my_templates_path, :notice => "Your template, #{@template.name}, has been deleted"
    else
      render :edit
    end
  end

  private

  def find_template
    @template ||= current_account.templates.find_by_slug!(params[:id])
  end
end

app/views/my_templates/_screenshot.html.haml
%li{ :id => "screenshot-#{screenshot.id}", :class => 'thumb' }
  = image_tag screenshot.image.thumb.url
  = link_to 'Delete', screenshot_path(screenshot.template, screenshot), :method => :delete

app/views/my_templates/_template.html.haml
%li{:id => "template-#{template.id}", :class => :template}
  %a{:href => edit_template_path(template)}
    %p.title
      = truncate(template.name, :length => 30)
      %span.price= template.formatted_price
    - if template.screenshots.first
      = image_tag template.screenshots.first.image.thumb
    - else
      = image_tag Screenshot.new.image.thumb
    %p.description= truncate(template.name, :length => 255)

app/views/my_templates/edit.html.haml
#my_templates_edit
  %header
    %h2
      = @template.name
      .actions
        = link_to 'Delete Template', [:edit, @template], :class => 'btn delete', :method => :delete, :confirm => 'Are you sure you want to delete this template?'
      .notice

  .clone-status
    %span.status
      Last Git Status:
    %span.message
      #{@template.state_summary} 
      - if @template.state_message.present?
        \- #{@template.state_message}

  = simple_form_for @template, :url => edit_template_path do |f|
    .info
      = f.input :name, :placeholder => 'Template Name', :label => 'Template Name'
      = f.input :developer_cost, :placeholder => 'Template Price', :label => 'Template Price'
      - if @template.can_clone? || @template.has_clone_pending?
        = f.input :uri, :placeholder => 'URI', :label => 'URI', :readonly => @template.has_clone_pending?
      - else
        .string.input
          %label URI
          %p= @template.uri
      .readme
        %h3 readme
        = f.input :readme, :placeholder => 'readme'
    .screenshots
      %h3 Screenshots
      %ul
        = render :partial => 'screenshot', :collection => @template.screenshots
      -if @template.screenshots.count < 4
        = link_to 'Add a screenshot', new_screenshot_path(@template), :class => 'btn'
    = f.submit 'Update', :class => 'btn'
:javascript
  var model = new Igata.Models.MyTemplate({ id: #{@template.id}, state: #{@template.state} })
  new Igata.Views.MyTemplateEditForm({ model: model })

app/views/my_templates/index.html.haml
#my_templates
  %ul.steps
    %li.active= link_to 'My Templates', my_templates_path
    %li= link_to 'My Purchases', purchased_templates_path
  %ul.templates
    = render :partial => 'template', :collection => @templates
  = link_to 'Add Template', new_template_path, :class => 'btn'

app/views/my_templates/new.html.haml
#my_templates_new
  %h1 New Template
  %meta{:name => 'dyno_cost', :content => @template.dyno_cost_in_cents}
  %meta{:name => 'dyno_count', :content => @template.dyno_count}

  %ol.steps

  .preview

  = simple_form_for @template, :url => new_template_path, :validate => true, :html => { :class => 'hide-label', :multipart => true } do |f|
    .repository
      %p
        Where is the git repo for this template?
      .buttons
        = link_to 'Github', '#', :class => 'github-btn btn', :data => {:linked => current_account.github_identity.present?}
        %span or
        = link_to 'Enter manually', '#', :class => 'manual-btn btn'
      .github
        .repositories
          %h3
            Retrieving your repositories...
            %img{:src => '/assets/ajax-loader.gif' }

        = f.input :uri, :as => :hidden, :input_html => {:id => 'github_uri'}
        = f.input :github_organization, :as => :hidden
        = f.input :github_api_url, :as => :hidden
      .manual
        = f.input :uri, :placeholder => 'URI', :input_html => {:id => 'manual_uri'}
    .info
      = f.input :name, :placeholder => 'Template Name'
      = f.input :developer_cost, :placeholder => 'Template Price', :label => 'Template Price'
      .readme
        = f.input :readme, :placeholder => 'Write in Markdown. If no readme will take from README.md.'
    .screenshots
      %h3 Add Screenshots
      = f.input :screenshots_attributes, :as => :screenshots, :count => 4
      = f.submit 'Create', :class => 'btn'
:javascript
  $(function(){
    app = {};
    app.router = new Igata.Routers.MyTemplateNew();
    Backbone.history.start();
  });